import type { TeamContent } from "./types";

export const zhTeam: TeamContent = {
  headline: "连接风险、信息与决策",
  support:
    "BIFROST 把数据、模型与产品工程串成同一条桥。我们先让风险更早被看见，再把信号交到对的人手里。",
  philosophy: [
    {
      key: "anticipate",
      title: "Anticipate",
      support: "预见风险：在问题放大前，用信号与结构把不确定性压成可讨论的判断。",
    },
    {
      key: "connect",
      title: "Connect",
      support: "连接信息：消除部门与角色之间的摩擦，让同一事实服务不同决策场景。",
    },
    {
      key: "decide",
      title: "Decide",
      support: "推动决策：把洞察落到岗位动作上，形成可复盘、可迭代的行动闭环。",
    },
  ],
  capabilityBridge: {
    title: "能力桥",
    nodes: [
      { id: "business", label: "业务问题" },
      { id: "data", label: "数据理解" },
      { id: "model", label: "模型判断" },
      { id: "product", label: "产品设计" },
      { id: "system", label: "系统实现" },
      { id: "action", label: "决策行动" },
    ],
  },
  membersSectionTitle: "团队成员",
  membersSectionSupport: "三人协作覆盖数据智能、产品策略与 AI 工程。",
  bioComingSoonLabel: "简历内容待补充",
  members: [
    {
      slug: "kuang-xuan",
      displayName: "匡璇",
      role: "数据智能与模型策略",
      intro:
        "应用统计与人工智能方向研究者，专注推荐排序、智能决策与数据产品。把统计建模、深度学习与 AI Agent 接到真实业务问题上，让信号变成可执行判断。",
      monogram: "KX",
      bioComingSoon: false,
      education: [
        {
          school: "厦门大学",
          college: "经济学院",
          degree: "硕士",
          major: "应用统计 / 人工智能与数据科学",
          period: "2025–",
          keywords: [
            "高级计量经济学",
            "深度学习与人工智能",
            "高等统计学习",
            "高级金融学",
          ],
        },
        {
          school: "四川大学",
          college: "商学院",
          degree: "本科",
          major: "管理科学",
          period: "2021–2025",
          keywords: [
            "机器学习",
            "多元统计分析",
            "时间序列分析",
            "随机运筹学",
            "数据营销分析",
          ],
        },
      ],
      projects: [
        {
          slug: "taac-2026",
          title: "腾讯广告算法大赛 TAAC 2026",
          period: "2026.04–2026.05",
          role: "核心成员",
          summary:
            "广告推荐排序：HyFormer + RankMixer，训练加速、特征工程与目标域融合。",
          tech: [
            "PyTorch",
            "HyFormer",
            "RankMixer",
            "torch.compile",
            "BF16 AMP",
            "Numba",
          ],
          outcomes: [
            "落地训练与推理加速（torch.compile / BF16 / TF32 / Numba）",
            "构建哈希统计、周期时间与节假日特征",
            "目标域融合：按广告上下文动态加权多域历史序列",
          ],
        },
        {
          slug: "a-share-agent",
          title: "A股智能投研 Agent Skill",
          period: "2026.03–至今",
          role: "独立完成",
          summary:
            "将情绪周期、波浪、MACD、成交量与资金流向组织为可约束的投研 Agent 工作流。",
          tech: ["LLM", "Domain Rules", "Workflow", "Python"],
          outcomes: [
            "支持走势判断、观察池筛选、关键位置识别与复盘归因",
            "数据日期、行情来源、冲突信号与资金分层规则约束输出",
            "冲突信号显式暴露，降低自由文本胡编风险",
          ],
        },
        {
          slug: "news-recommendation",
          title: "新闻点击预测与召回排序",
          period: "2026.03–2026.04",
          role: "核心成员",
          summary: "多路召回 + 特征工程 + 多模型融合，生成用户 Top5 新闻推荐。",
          tech: ["Recall", "Ranking", "Feature Engineering", "Sequence Models"],
          outcomes: [
            "多路召回覆盖近期兴趣、相似用户、热点与长尾",
            "围绕「为何点击」构建差异化排序特征",
            "融合排序 / 分类 / 序列模型，结果进入 Top5",
          ],
        },
        {
          slug: "cnki-pipeline",
          title: "知网基金成果采集与数据治理",
          period: "2026.01–2026.04",
          role: "核心成员",
          summary:
            "经管期刊基金成果：清洗、采集与缺口自动补采流水线。",
          tech: ["Python", "Pandas", "Selenium", "OpenCV"],
          outcomes: [
            "覆盖 175 本期刊",
            "沉淀百万级结构化数据资产",
            "缺口统计与自动补采闭环",
          ],
        },
        {
          slug: "customer-clustering",
          title: "外卖行业客户细分（聚类集成选择）",
          period: "2025.01–2025.06",
          role: "独立完成",
          summary:
            "基于聚类集成选择的外卖客户细分研究，完成群体划分与结果分析。",
          tech: ["Python", "Clustering", "WHCD", "Text Mining"],
          outcomes: [
            "样本 9763 条美团评论",
            "应用 WHCD 聚类完成客户群体划分",
            "形成可解释的细分画像结论",
          ],
        },
      ],
      skills: [
        {
          id: "analytics",
          label: "数据分析",
          items: ["SQL", "Pandas", "Tableau", "数据营销分析"],
        },
        {
          id: "stats",
          label: "统计建模",
          items: ["计量经济学", "多元统计", "时间序列", "随机运筹"],
        },
        {
          id: "ml",
          label: "机器学习",
          items: ["Python", "PyTorch", "推荐排序", "序列建模"],
        },
        {
          id: "ai-workflow",
          label: "AI 工作流",
          items: ["LLM Agent", "Codex", "Claude", "Gemini", "DeepSeek"],
        },
        {
          id: "data-eng",
          label: "数据工程",
          items: ["Selenium", "OpenCV", "自动化采集", "数据治理"],
        },
      ],
      awards: [
        { title: "全国大学生数学竞赛省一等奖" },
        { title: "统计建模省二等奖" },
        { title: "学创杯创业综合模拟大赛校级三等奖" },
        { title: "CET-4" },
        { title: "CET-6" },
      ],
    },
    {
      slug: "member-b",
      displayName: "何珂一",
      role: "产品策略与全球增长",
      intro: "管理经济学与数据科学背景，专注 AI 产品设计、全球增长与商业策略。善于把市场研究、用户洞察和数据分析转化为产品方案，并推动跨团队协作与试点落地。",
      monogram: "HKY",
      bioComingSoon: false,
      education: [
        {
          school: "新加坡南洋理工大学",
          college: "南洋公共管理研究生院",
          degree: "硕士",
          major: "管理经济学",
          period: "2026.01–2027.01",
          keywords: ["数据分析", "微观经济学", "商业政策", "战略管理"],
        },
        {
          school: "对外经济贸易大学",
          college: "信息学院 / 统计学院",
          degree: "双学士",
          major: "数据科学与大数据技术 / 经济统计",
          period: "2020.09–2024.06",
          keywords: ["机器学习", "Python", "商业预测", "网络营销", "国际商务谈判"],
        },
      ],
      projects: [
        {
          slug: "shopfront-sg",
          title: "Chua Thian Poh Pinnacle Prize 2026 — ShopFrontSG",
          period: "2026.03–至今",
          role: "市场战略与产品负责人",
          summary: "围绕新加坡社会影响力目标完成市场筛选、核心战略设计与 AI 辅助 MVP 产品方案，并推动线下试点与创业路演。",
          tech: ["Product Strategy", "Codex", "Claude Code", "MVP", "Business Plan"],
          outcomes: ["分析 a16z 千余份投资标的并筛选 40 家核心企业", "主导 AI 辅助 MVP、终审视频与产品技术文档", "晋级全国 10 强总决赛并获得孵化资源关注"],
        },
        {
          slug: "guanglun-global-strategy",
          title: "光轮智能全球资源与战略",
          period: "2026.06–至今",
          role: "全球资源与战略实习",
          summary: "以 AI 工具搭建海外供应商资源看板，负责供应商入驻、匹配、议价、项目跟进与风险评估。",
          tech: ["Claude Code", "Codex", "Supplier Operations", "Risk Analysis"],
          outcomes: ["对接全球 30 余家海外供应商", "完成 20 余家供应商数据整合与风险评估", "整理超过 80 万条结构化数据"],
        },
        {
          slug: "eazo-global-growth",
          title: "EAZO AI 全球增长",
          period: "2026.06–2026.07",
          role: "全球增长与战略实习",
          summary: "面向全球创作者开展市场调研、标准化触达、合作转化与 AI 应用原型验证。",
          tech: ["Growth Strategy", "Creator Operations", "AI Prototyping", "Outreach"],
          outcomes: ["触达 3000 余名全球创作者", "沉淀 2000+ 创作者资源并促成 20 余位正式合作", "筛选 100 人进入官方签约计划"],
        },
        {
          slug: "market-research-competition",
          title: "全国大学生市场调查与分析大赛",
          period: "2021.11–2022.04",
          role: "数据与战略分析负责人",
          summary: "围绕大学生一人食外卖需求完成研究设计、问卷分析、用户画像和产品营销建议。",
          tech: ["Python", "SPSS", "Tableau", "Survey Design"],
          outcomes: ["回收 500+ 份有效问卷", "完成数据清洗、假设检验与用户画像", "获北京赛区一等奖"],
        },
      ],
      skills: [
        { id: "analytics", label: "商业分析", items: ["市场研究", "行业研究", "Tableau", "SPSS"] },
        { id: "stats", label: "数据方法", items: ["Python", "SQL", "统计分析", "商业预测"] },
        { id: "ml", label: "AI 产品", items: ["产品设计", "MVP", "Agent 设计", "Vibe Coding"] },
        { id: "ai-workflow", label: "AI 工作流", items: ["ChatGPT", "Codex", "Claude", "Gemini", "DeepSeek"] },
        { id: "data-eng", label: "增长与协作", items: ["全球增长", "策略运营", "商务谈判", "跨团队协作"] },
      ],
      awards: [
        { title: "全国大学生数学建模竞赛北京赛区一等奖" },
        { title: "全国大学生数学建模竞赛北京赛区二等奖" },
        { title: "全国大学生市场调查与分析大赛北京赛区一等奖" },
        { title: "CDA 数据分析师 Level I & II" },
      ],
    },
    {
      slug: "member-c",
      displayName: "朱浩然",
      role: "数据分析与算法工程",
      intro: "管理科学与数据分析背景，关注搜索广告、推荐系统与实证研究。能够从数据清洗和指标构建出发，完成特征工程、模型验证与业务解释，把算法实验转化为可复用的分析流程。",
      monogram: "ZHR",
      bioComingSoon: false,
      education: [
        {
          school: "西安交通大学",
          college: "管理学院",
          degree: "硕士",
          major: "管理科学",
          period: "2025.09–至今",
          keywords: ["机器学习", "复杂数据统计分析", "计量经济学", "时间序列分析", "数据驱动建模与优化"],
        },
        {
          school: "四川大学",
          college: "商学院",
          degree: "本科",
          major: "管理科学",
          period: "本科阶段",
          keywords: ["GPA 3.73/4.00", "专业排名 4/34", "Python", "R 语言", "营销数据分析"],
        },
      ],
      projects: [
        {
          slug: "search-ads-conversion",
          title: "搜索广告转化预估与行为建模",
          period: "2026.04–2026.05",
          role: "团队项目",
          summary: "基于官方 baseline 优化数据读取、序列处理和训练配置，并围绕搜索广告场景补充周期时间、节假日与历史转化倾向特征。",
          tech: ["Python", "Feature Engineering", "Sequence Modeling", "Target Encoding"],
          outcomes: ["缩短实验反馈时间", "构造小时、星期、周期、节假日与真实休息日特征", "引入目标广告上下文并按时间段与稀疏度拆分验证"],
        },
        {
          slug: "news-app-recommendation",
          title: "新闻 APP 点击预测与召回排序",
          period: "推荐系统实战",
          role: "个人项目",
          summary: "面向陌生用户和长尾文章池构建多路召回、特征工程与模型融合流程，生成 Top5 新闻推荐。",
          tech: ["Recall", "Ranking", "Classification", "Sequence Models"],
          outcomes: ["组合近期点击、相似用户、热门、内容相似与时间规则召回", "构建用户兴趣、活跃度、设备与文章热度特征", "融合排序、分类与序列模型结果"],
        },
        {
          slug: "online-healthcare-pricing",
          title: "在线医疗平台价格差异与医生参与行为",
          period: "2024.09–2025.05",
          role: "实证研究",
          summary: "研究线上线下问诊价格差异对医生退单和内容参与的影响，并检验社会性与财务性平台反馈的调节作用。",
          tech: ["Econometrics", "Data Matching", "Hypothesis Testing", "Platform Research"],
          outcomes: ["匹配 4,203 名医生线下普通门诊价格", "构造价格差异与高定价变量", "识别价格锚点及社会性回报的调节效应"],
        },
      ],
      skills: [
        { id: "analytics", label: "数据分析", items: ["Python", "SQL", "R", "Pandas"] },
        { id: "stats", label: "统计建模", items: ["计量经济学", "时间序列", "多元统计", "假设检验"] },
        { id: "ml", label: "机器学习", items: ["推荐系统", "特征工程", "序列建模", "模型验证"] },
        { id: "ai-workflow", label: "AI 工作流", items: ["实验设计", "数据清洗", "指标构建", "结果解释"] },
        { id: "data-eng", label: "分析工程", items: ["样本处理", "统计口径控制", "训练配置", "可复用流程"] },
      ],
      awards: [
        { title: "全国大学生数学竞赛省级二等奖" },
        { title: "清华 IE 亮剑国家级三等奖" },
        { title: "国家励志奖学金（2024）" },
        { title: "四川大学综合奖学金（2022、2023）" },
        { title: "CET-6 543" },
      ],
    },
  ],
};
